# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :compressed

# Site settings
title:             "Bitcoin Core PR Review Club"
description:       "A weekly review club for Bitcoin Core PRs"
author:            "Bitcoin Core PR Review Club contributors"
meeting_time:      "17:00 UTC"
meeting_day:       "Wednesday"
meeting_location:  "#bitcoin-core-pr-reviews IRC channel on <a href=\"https://webchat.freenode.net\">freenode</a>"
url: https://bitcoincore.reviews
twitter_username: BitcoinCorePRs
twitter:
  card: summary
  username: BitcoinCorePRs

# Exclude from processing
exclude:
   - CONTRIBUTING.md
   - Gemfile
   - Gemfile.lock
   - Makefile
   - README.md
   - Rakefile
   - test/

defaults:
  - scope:
      path: ""  ## all pages
    values:
      image: /assets/img/twitter_card.png
