title: 'Bitcoin Core PR Review Club'
tagline: 'A weekly review club for Bitcoin Core PRs'

author:
  name: 'John Newbery'

menu:
# Uncomment to activate the menu looping function in the header.html file under _includes
- {name: 'Home', url: ''}
- {name: 'Meetings', url: 'meetings/'}

social:
# Uncomment to activate the social media icon looping function in the footer.html file under _includes
#- {icon: 'github', link: 'https://www.github.com/lenpaul'}
